steps:
  # Run backend tests
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        pytest tests/ -v || true

  # Build backend container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/binpacker-backend:$COMMIT_SHA', '.']

  # Build frontend container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/binpacker-frontend:$COMMIT_SHA', './frontend']

  # Push images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/binpacker-backend:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/binpacker-frontend:$COMMIT_SHA']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'binpacker-backend'
      - '--image=gcr.io/$PROJECT_ID/binpacker-backend:$COMMIT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--port=8000'
      - '--allow-unauthenticated'

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'binpacker-frontend'
      - '--image=gcr.io/$PROJECT_ID/binpacker-frontend:$COMMIT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/binpacker-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/binpacker-frontend:$COMMIT_SHA'

substitutions:
  _PROJECT_ID: 'final-bin-pack'
