# BinPacker Cloud App - Docker Compose for Local Development
version: '3.8'

services:
  # Backend API Service
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/binpacker
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    depends_on:
      - postgres
    restart: unless-stopped

  # Frontend Service (will be added in Step 2)
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - backend
  #   restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: binpacker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # Redis Cache (for future optimization results caching)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  # pgAdmin for database management (development only)
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@binpacker.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    profiles:
      - dev

volumes:
  postgres_data:

networks:
  default:
    name: binpacker-network